spring:
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/esm_stdio1
    jpa:
        show-sql: true
        properties:
          hibernate:
              format_sql: true
    mvc:
        pathmatch:
            matching-strategy: ant_path_matcher
application:
    security:
        password-secret: "ESM"
        duration-accessToken: 604800000
        duration-refreshToken: 1036800000
server:
    port: 8080